package:
  name: singlemolecule
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - bhmm
    - six

  run:
    - python
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - bhmm
    - six

test:
  requires:
    - nose
  imports:
    - singlemolecule

about:
  home: https://github.com/bhmm/singlemolecule
  license: GNU Lesser General Public License v2 or later (LGPLv2+)




